<script src="https://cdn.staticfile.org/jquery/1.10.2/jquery.min.js"></script>
<script>
// let p=new Promise((resolve,reject)=>{
//   $.ajax({
//       url:"mock/user.json",
//       success:(data)=>{
//            console.log(data)
//            resolve(data)
//       },
//      error:(err)=>{
//         console.log(err) 
//         reject(err)
//      } 
//   })
// })
// p.then((obj)=>{
//   return new Promise((resolve,reject)=>{
//    $.ajax({
//        url:"mock/user_corse_"+obj.id+".json",
//        success:(data)=>{
//         console.log(data)
//         resolve(data)
//        },
//        error:(err)=>{
//         console.log(err) 
//         reject(err)
//        }
//    })
//   })
// }).then((data)=>{
//     $.ajax({
//        url:"mock/user_score_"+data.id+".json",
//        success:(data)=>{
//         console.log(data)
//        },
//        error:(err)=>{
//         console.log(err) 
//        }
//    })
// })


//套娃怎么说，有多少请求套多少请求怎么说
//Promise  如果成功调用resolve方法传入参数就是 promise对象.then((data)) 中的data  ，如果调用reject方法传入参数，传入参数的值为promise对象的。catch((data))中的data

let get=(url)=>{
    return new Promise((resolve,reject)=>{
         $.ajax({
          url:url,
          success:(data)=>{
            resolve(data)
          },
          error:(err)=>{
              reject(data)
          }
         })
    });
}

get("mock/user.json").then((obj)=>{
    console.log(obj)
    get("mock/user_corse_"+obj.id+".json").then(
    (data)=>{
        console.log(data)
      get("mock/user_score_"+data.id+".json").then((data)=>{
        console.log(data)
      }).catch((err)=>{
        console.log(err)
      })
    }
    )
})

let fun=(num)=>{
    return new Promise((resolve,reject)=>{
        if(num>1){
            resolve(num)
        }
        else{
            reject(num)
        }
    })
}


fun(3).then((data)=>{
    console.log("输入的是正整数"+data)
}).catch((data)=>{
    console.log("输入的是负整数"+data)
})





</script>